{"code":"42703","driverError":{"code":"42703","file":"parse_relation.c","length":113,"line":"3716","name":"error","position":"204","routine":"errorMissingColumn","severity":"ERROR"},"file":"parse_relation.c","length":113,"level":"error","line":"3716","message":"Unhandled error: column User.userAgent does not exist","parameters":["test@test.com"],"position":"204","query":"SELECT \"User\".\"id\" AS \"User_id\", \"User\".\"name\" AS \"User_name\", \"User\".\"email\" AS \"User_email\", \"User\".\"password\" AS \"User_password\", \"User\".\"role\" AS \"User_role\", \"User\".\"is_active\" AS \"User_is_active\", \"User\".\"userAgent\" AS \"User_userAgent\", \"User\".\"created_at\" AS \"User_created_at\", \"User\".\"updated_at\" AS \"User_updated_at\" FROM \"users\" \"User\" WHERE ((\"User\".\"email\" = $1)) LIMIT 1","routine":"errorMissingColumn","severity":"ERROR","stack":"QueryFailedError: column User.userAgent does not exist\n    at PostgresQueryRunner.query (C:\\Users\\Admin\\Desktop\\test-cloudmedia\\test-cloudmedia\\cloud-media-backend\\node_modules\\typeorm\\src\\driver\\postgres\\PostgresQueryRunner.ts:331:19)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async SelectQueryBuilder.loadRawResults (C:\\Users\\Admin\\Desktop\\test-cloudmedia\\test-cloudmedia\\cloud-media-backend\\node_modules\\src\\query-builder\\SelectQueryBuilder.ts:3805:25)\n    at async SelectQueryBuilder.executeEntitiesAndRawResults (C:\\Users\\Admin\\Desktop\\test-cloudmedia\\test-cloudmedia\\cloud-media-backend\\node_modules\\src\\query-builder\\SelectQueryBuilder.ts:3551:26)\n    at async SelectQueryBuilder.getRawAndEntities (C:\\Users\\Admin\\Desktop\\test-cloudmedia\\test-cloudmedia\\cloud-media-backend\\node_modules\\src\\query-builder\\SelectQueryBuilder.ts:1670:29)\n    at async SelectQueryBuilder.getOne (C:\\Users\\Admin\\Desktop\\test-cloudmedia\\test-cloudmedia\\cloud-media-backend\\node_modules\\src\\query-builder\\SelectQueryBuilder.ts:1697:25)\n    at async AuthService.register (C:\\Users\\Admin\\Desktop\\test-cloudmedia\\test-cloudmedia\\cloud-media-backend\\src\\services\\auth.service.ts:13:26)\n    at async C:\\Users\\Admin\\Desktop\\test-cloudmedia\\test-cloudmedia\\cloud-media-backend\\src\\routes\\auth.ts:11:20","timestamp":"2024-11-04T15:10:59.312Z"}
{"code":"ECONNREFUSED","level":"error","message":"Error starting server:","stack":"AggregateError\n    at internalConnectMultiple (node:net:1121:18)\n    at afterConnectMultiple (node:net:1688:7)","timestamp":"2024-11-05T08:13:54.897Z"}
